# Generated by Django 6.0 on 2025-12-16 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon Cabinet', max_length=200, verbose_name='Nom du cabinet')),
                ('description', models.TextField(blank=True, verbose_name='Description / Savoir-faire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cabinet/branding/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Logo')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Format HEX (ex: #6366f1)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#ec4899', help_text='Format HEX (ex: #ec4899)', max_length=7, verbose_name='Couleur secondaire')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du Cabinet',
                'verbose_name_plural': 'Paramètres du Cabinet',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle / Titre')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cabinet/team/', verbose_name='Photo')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': 'Équipe',
                'ordering': ['order', 'name'],
            },
        ),
    ]
