# Generated by Django 6.0 on 2025-12-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Ex: Lundi-Vendredi: 9h-18h', verbose_name="Horaires d'ouverture"),
        ),
    ]
