# Generated by Django 6.0 on 2025-12-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_cabinet_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='history',
            field=models.TextField(blank=True, help_text='Histoire et origine du cabinet', verbose_name='Historique du cabinet'),
        ),
    ]
