# Generated by Django 6.0 on 2026-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_cabinet_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobile (Cellulaire)'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
    ]
