# Generated by Django 6.0.1 on 2026-02-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_cabinet_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
    ]
