# Generated by Django 6.0.1 on 2026-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_cabinet_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='primary_color',
            field=models.CharField(default='#1a237e', help_text='Format HEX (ex: #1a237e)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='secondary_color',
            field=models.CharField(default='#c2185b', help_text='Format HEX (ex: #c2185b)', max_length=7, verbose_name='Couleur secondaire'),
        ),
    ]
