# Generated by Django 6.0.1 on 2026-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_teammember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='consultation_fees',
            field=models.TextField(blank=True, help_text='Détails des tarifs', verbose_name='Honoraires & Consultations'),
        ),
    ]
