# Generated by Django 6.0.1 on 2026-02-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_cabinet_consultation_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='N° SIRET'),
        ),
    ]
