# Generated by Django 6.0 on 2025-12-04 21:04

import django.contrib.postgres.search
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('VIEW', 'Consultation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('DOWNLOAD', 'Téléchargement'), ('SHARE', 'Partage'), ('PERMISSION', 'Changement de permission')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Intitulé de l'affaire")),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence dossier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('CLOS', 'Clos'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('opened_date', models.DateField(verbose_name="Date d'ouverture")),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('client_type', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('ASSOCIATION', 'Association')], default='PARTICULIER', max_length=20, verbose_name='Type de client')),
                ('company_registration', models.CharField(blank=True, max_length=100, verbose_name='N° SIRET/SIREN')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_type', models.CharField(choices=[('CONTRAT', 'Contrat'), ('COURRIER', 'Courrier'), ('JUGEMENT', 'Jugement'), ('PIECE', 'Pièce'), ('NOTE', 'Note'), ('MEMOIRE', 'Mémoire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Fichier')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.BigIntegerField(verbose_name='Taille (octets)')),
                ('file_extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Texte extrait (OCR)')),
                ('ocr_processed', models.BooleanField(default=False, verbose_name='OCR traité')),
                ('ocr_error', models.TextField(blank=True, verbose_name='Erreur OCR')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='Vecteur de recherche')),
                ('is_confidential', models.BooleanField(default=True, verbose_name='Confidentiel')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('READ', 'Lecture'), ('WRITE', 'Écriture'), ('DELETE', 'Suppression'), ('ADMIN', 'Administration')], default='READ', max_length=10, verbose_name='Niveau de permission')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'octroi")),
            ],
            options={
                'verbose_name': 'Permission Document',
                'verbose_name_plural': 'Permissions Documents',
            },
        ),
    ]
