# Generated by Django 6.0 on 2025-12-04 21:04

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.case', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='documents.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.case', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='documents.document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='documents_c_name_11af9a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='documents_c_created_11f5de_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['reference'], name='documents_c_referen_6491c1_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='documents_c_status_9f7148_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['opened_date'], name='documents_c_opened__734685_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_name'], name='documents_d_file_na_42a6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_d_search__05a045_gin'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='documents_a_user_id_481fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='documents_a_action_a46f00_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='documents_a_timesta_0c4e02_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['user', 'permission_level'], name='documents_d_user_id_689161_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'user')},
        ),
    ]
