# Generated by Django 6.0 on 2025-12-04 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cases', to='documents.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('deadline_type', models.CharField(choices=[('AUDIENCE', 'Audience'), ('DEPOT', 'Dépôt de pièce'), ('REPONSE', 'Réponse à notifier'), ('DELAI', 'Délai de recours'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'échéance")),
                ('due_date', models.DateTimeField(verbose_name="Date d'échéance")),
                ('reminder_days', models.IntegerField(default=7, verbose_name='Rappel (jours avant)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='documents.case', verbose_name='Dossier')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines_completed', to=settings.AUTH_USER_MODEL, verbose_name='Complété par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['due_date'], name='documents_d_due_dat_bfff21_idx'), models.Index(fields=['is_completed'], name='documents_d_is_comp_0408b6_idx'), models.Index(fields=['case', 'due_date'], name='documents_d_case_id_3f9dcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Numéro de version')),
                ('file', models.FileField(upload_to='document_versions/', verbose_name='Fichier')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.BigIntegerField(verbose_name='Taille du fichier')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Version de Document',
                'verbose_name_plural': 'Versions de Documents',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', '-version_number'], name='documents_d_documen_654958_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
