# Generated by Django 6.0 on 2025-12-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CIVIL', 'Civil (Jaune)'), ('CORRECTIONNEL', 'Correctionnel (Bleu)')], default='CIVIL', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='action_requested',
            field=models.TextField(blank=True, verbose_name='Diligence à faire'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='courtroom',
            field=models.CharField(blank=True, max_length=100, verbose_name="Salle d'audience"),
        ),
        migrations.AddField(
            model_name='deadline',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=255, verbose_name='Juridiction'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='result',
            field=models.TextField(blank=True, verbose_name='Résultat'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadline_type',
            field=models.CharField(choices=[('AUDIENCE', 'Audience'), ('DEPOT', 'Dépôt de pièce'), ('REPONSE', 'Réponse à notifier'), ('DELAI', 'Délai de recours'), ('CONGES', 'Congés / Suspension'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'échéance"),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre / Objet'),
        ),
    ]
