# Generated by Django 6.0 on 2026-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_case_category_deadline_action_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('CORRECTIONNEL', 'Correctionnel')], default='CIVIL', max_length=20, verbose_name='Catégorie'),
        ),
    ]
