# Generated by Django 6.0 on 2026-01-08 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cases', to='documents.case', verbose_name='Dossier principal'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONTRAT', 'Contrat'), ('COURRIER', 'Courrier'), ('JUGEMENT', 'Jugement'), ('PIECE', 'Pièce'), ('NOTE', 'Note'), ('MEMOIRE', 'Mémoire'), ('ASSIGNATION', 'Assignation'), ('CONCLUSION', 'Conclusion'), ('REQUETE', 'Requête'), ('ACTE_HUISSIER', 'Acte d’huissier'), ('DOSSIER_ADVERSE', 'Dossier partie adverse'), ('CITATION', 'Citation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document'),
        ),
    ]
