# Generated by Django 6.0 on 2026-01-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_case_parent_case_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='adverse_lawyer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Avocat adverse'),
        ),
        migrations.AddField(
            model_name='case',
            name='adverse_party',
            field=models.CharField(blank=True, max_length=255, verbose_name='Partie adverse'),
        ),
        migrations.AddField(
            model_name='case',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence (Numéro)'),
        ),
        migrations.AddField(
            model_name='case',
            name='represented_party',
            field=models.CharField(blank=True, max_length=255, verbose_name='Partie représentée'),
        ),
    ]
