# Generated by Django 6.0 on 2026-01-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_case_adverse_lawyer_case_adverse_party_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notification envoyée'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Attention'), ('ERROR', 'Erreur')], default='INFO', max_length=10, verbose_name='Niveau')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('entity_type', models.CharField(choices=[('CASE', 'Dossier'), ('DOCUMENT', 'Document'), ('DEADLINE', 'Échéance'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=20, verbose_name="Type d'entité")),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'entité")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='documents_n_user_id_02e99a_idx'), models.Index(fields=['user', '-created_at'], name='documents_n_user_id_c8303a_idx')],
            },
        ),
    ]
