# Generated by Django 6.0 on 2026-01-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_deadline_notification_sent_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Description de la diligence')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligences', to='documents.case', verbose_name='Dossier associé')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligences_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Diligence',
                'verbose_name_plural': 'Diligences',
                'ordering': ['is_completed', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'is_completed'], name='documents_d_created_0ffed4_idx')],
            },
        ),
    ]
