# Generated by Django 6.0 on 2026-01-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_diligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='fees',
            field=models.TextField(blank=True, verbose_name='Honoraires'),
        ),
        migrations.AddField(
            model_name='case',
            name='our_lawyers',
            field=models.TextField(blank=True, verbose_name='Avocats à mes côtés'),
        ),
        migrations.AlterField(
            model_name='case',
            name='adverse_lawyer',
            field=models.TextField(blank=True, verbose_name='Avocat(s) partie adverse'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('COMMERCIAL', 'Commercial'), ('SOCIAL', 'Social'), ('PENAL', 'Pénal'), ('CORRECTIONNEL', 'Correctionnel')], default='CIVIL', max_length=20, verbose_name='Catégorie'),
        ),
    ]
