# Generated by Django 6.0 on 2026-01-28 15:46

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_case_title_alter_notification_entity_type_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models.document_upload_path, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(max_length=500, upload_to='document_versions/', verbose_name='Fichier'),
        ),
    ]
