# Generated by Django 6.0.1 on 2026-02-10 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_file_alter_documentversion_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('INSTANCE', 'Instance'), ('APPEL', 'Appel'), ('POURVOI', 'Pourvoi')], max_length=20, verbose_name='Type de décision')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de la décision')),
                ('juridiction', models.CharField(blank=True, max_length=255, verbose_name='Juridiction')),
                ('numero_decision', models.CharField(blank=True, max_length=100, verbose_name='Numéro de la décision')),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat / Dispositif')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='documents.case', verbose_name='Dossier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Décision',
                'verbose_name_plural': 'Décisions',
                'ordering': ['decision_type', 'date_decision'],
                'indexes': [models.Index(fields=['case', 'decision_type'], name='documents_d_case_id_185a73_idx')],
            },
        ),
    ]
