# Generated by Django 6.0.1 on 2026-02-11 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('AUDIENCE', 'Audience'), ('RDV', 'Rendez-vous client'), ('REUNION', 'Réunion'), ('DEPLACEMENT', 'Déplacement'), ('RAPPEL', 'Rappel'), ('CONFERENCE', 'Conférence'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], default='RDV', max_length=20, verbose_name="Type d'événement")),
                ('start_datetime', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Journée entière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur')),
                ('reminder_minutes', models.IntegerField(blank=True, null=True, verbose_name='Rappel (minutes avant)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, verbose_name='Règle de récurrence')),
                ('year', models.IntegerField(verbose_name="Année d'archivage")),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to='documents.case', verbose_name='Dossier lié')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Événement d'agenda",
                'verbose_name_plural': "Événements d'agenda",
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['year', 'start_datetime'], name='documents_a_year_c8b9be_idx'), models.Index(fields=['event_type'], name='documents_a_event_t_6d1964_idx'), models.Index(fields=['case'], name='documents_a_case_id_6160f6_idx'), models.Index(fields=['created_by', 'year'], name='documents_a_created_8c2cb1_idx')],
            },
        ),
    ]
