# Generated by Django 6.0.1 on 2026-02-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_agendaevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='decision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_deadline', to='documents.decision', verbose_name='Décision associée'),
        ),
    ]
