# Generated by Django 6.0.1 on 2026-02-13 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_deadline_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('REPORT', 'Report'), ('ANNULATION', 'Annulation'), ('TERMINATION', 'Terminé'), ('SUPPRESSION', 'Suppression')], max_length=20, verbose_name="Type d'action")),
                ('ancienne_valeur', models.JSONField(blank=True, null=True, verbose_name='État avant modification')),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True, verbose_name='État après modification')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
            ],
            options={
                'verbose_name': "Historique d'agenda",
                'verbose_name_plural': "Historiques d'agenda",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='AgendaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('7_JOURS', '7 jours avant'), ('3_JOURS', '3 jours avant'), ('1_JOUR', '1 jour avant'), ('2_HEURES', '2 heures avant')], max_length=10, verbose_name='Type de rappel')),
                ('date_envoi_prevue', models.DateTimeField(verbose_name="Date d'envoi prévue")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHOUEE', 'Échouée')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('date_envoi_effectif', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi effective")),
            ],
            options={
                'verbose_name': "Notification d'agenda",
                'verbose_name_plural': "Notifications d'agenda",
                'ordering': ['date_envoi_prevue'],
            },
        ),
        migrations.AlterModelOptions(
            name='agendaevent',
            options={'ordering': ['date_audience', 'heure_audience'], 'verbose_name': "Entrée d'agenda", 'verbose_name_plural': "Entrées d'agenda"},
        ),
        migrations.RemoveIndex(
            model_name='agendaevent',
            name='documents_a_year_c8b9be_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendaevent',
            name='documents_a_event_t_6d1964_idx',
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='date_audience',
            field=models.DateField(default='2026-01-01', verbose_name="Date de l'audience"),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='dossier_nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom du dossier / parties'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='dossier_numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de dossier'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='heure_audience',
            field=models.TimeField(default='09:00', verbose_name="Heure de l'audience"),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='motif_report',
            field=models.TextField(blank=True, verbose_name='Motif du report'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes et observations'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='reporte_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_suivants', to='documents.agendaevent', verbose_name="Reporté depuis (audience d'origine)"),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='statut',
            field=models.CharField(choices=[('PREVU', 'Prévu'), ('REPORTE', 'Reporté'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PREVU', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='type_chambre',
            field=models.CharField(choices=[('CA_CORRECTIONNEL', 'CA Correctionnel'), ('CA_CRIMINELLE', 'CA Criminelle'), ('CA_SOCIAL', 'CA Social'), ('TRIBUNAL_TRAVAIL', 'Tribunal Travail'), ('FDTR', 'FDTR'), ('TRIBUNAL_COMMERCE', 'Tribunal de Commerce'), ('TRIBUNAL_INSTANCE', "Tribunal d'Instance"), ('TRIBUNAL_GRANDE_INSTANCE', 'Tribunal de Grande Instance'), ('COUR_SUPREME', 'Cour Suprême'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='Type de chambre'),
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='type_chambre_autre',
            field=models.CharField(blank=True, help_text='Si "Autre" est sélectionné, précisez ici.', max_length=100, verbose_name='Chambre (autre)'),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='color',
            field=models.CharField(default='#2196f3', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='event_type',
            field=models.CharField(choices=[('AUDIENCE', 'Audience'), ('RDV', 'Rendez-vous client'), ('REUNION', 'Réunion'), ('DEPLACEMENT', 'Déplacement'), ('AUTRE', 'Autre')], default='AUDIENCE', max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='start_datetime',
            field=models.DateTimeField(help_text='Calculé automatiquement depuis date_audience + heure_audience', verbose_name='Date et heure de début'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['year', 'date_audience'], name='documents_a_year_dbec35_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['type_chambre'], name='documents_a_type_ch_70e7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['statut'], name='documents_a_statut_16f626_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['dossier_numero'], name='documents_a_dossier_06ca11_idx'),
        ),
        migrations.AddField(
            model_name='agendahistory',
            name='agenda_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='documents.agendaevent', verbose_name="Entrée d'agenda"),
        ),
        migrations.AddField(
            model_name='agendahistory',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='agendanotification',
            name='agenda_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.agendaevent', verbose_name="Entrée d'agenda"),
        ),
        migrations.AddField(
            model_name='agendanotification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur à notifier'),
        ),
        migrations.RemoveField(
            model_name='agendaevent',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='agendaevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='agendaevent',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='agendaevent',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='agendaevent',
            name='reminder_minutes',
        ),
        migrations.AlterUniqueTogether(
            name='agendanotification',
            unique_together={('agenda_entry', 'utilisateur', 'type_notification')},
        ),
    ]
