# Generated by Django 6.0.1 on 2026-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_agendahistory_agendanotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevent',
            name='date_audience',
            field=models.DateField(verbose_name="Date de l'audience"),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='heure_audience',
            field=models.TimeField(verbose_name="Heure de l'audience"),
        ),
    ]
