# Generated by Django 6.0.1 on 2026-02-13 20:59

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_agendaevent_date_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_multi_page',
            field=models.BooleanField(default=False, verbose_name='Multi-pages'),
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=documents.models.document_page_upload_path, verbose_name='Fichier de la page')),
                ('page_number', models.PositiveIntegerField(verbose_name='Numéro de page')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Texte OCR de la page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Page de document',
                'verbose_name_plural': 'Pages de document',
                'ordering': ['page_number'],
            },
        ),
    ]
