# Generated by Django 6.0.1 on 2026-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_is_multi_page_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='cabinet_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Cabinet'),
        ),
        migrations.AddField(
            model_name='decision',
            name='infraction_motif',
            field=models.TextField(blank=True, verbose_name='Infraction / Motif'),
        ),
        migrations.AddField(
            model_name='decision',
            name='mesure',
            field=models.TextField(blank=True, verbose_name='Mesure'),
        ),
        migrations.AddField(
            model_name='decision',
            name='section',
            field=models.CharField(choices=[('GENERALE', 'Décisions Générales'), ('CABINET_INSTRUCTION', "Cabinets d'Instruction"), ('TI_FAMILLE', 'TI Famille')], default='GENERALE', max_length=50, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='type_chambre',
            field=models.CharField(choices=[('TI_DAKAR', 'TI Dakar'), ('TI_PIKINE', 'TI Pikine'), ('TI_GUEDIAWAYE', 'TI Guédiawaye'), ('TI_RUFISQUE', 'TI Rufisque'), ('TI_KEUR_MASSAR', 'TI Keur Massar'), ('TGI_DAKAR_CIVIL', 'TGI Dakar - Civil'), ('TGI_DAKAR_STATUT_PERSONNEL', 'TGI Dakar - Statut Personnel'), ('TGI_DAKAR_FDTR', 'TGI Dakar - FDTR'), ('TGI_DAKAR_CORRECTIONNELLE', 'TGI Dakar - Correctionnelle'), ('TGI_DAKAR_INSTRUCTION', 'TGI Dakar - Instruction'), ('TGI_PIKINE_CIVIL', 'TGI Pikine - Civil'), ('TGI_PIKINE_FDTR', 'TGI Pikine - FDTR'), ('TGI_PIKINE_CORRECTIONNELLE', 'TGI Pikine - Correctionnelle'), ('TGI_PIKINE_INSTRUCTION', 'TGI Pikine - Instruction'), ('TGI_GUEDIAWAYE_CIVIL', 'TGI Guédiawaye - Civil'), ('TGI_GUEDIAWAYE_FDTR', 'TGI Guédiawaye - FDTR'), ('TGI_GUEDIAWAYE_CORRECTIONNELLE', 'TGI Guédiawaye - Correctionnelle'), ('TGI_GUEDIAWAYE_INSTRUCTION', 'TGI Guédiawaye - Instruction'), ('TGI_RUFISQUE_CIVIL', 'TGI Rufisque - Civil'), ('TGI_RUFISQUE_FDTR', 'TGI Rufisque - FDTR'), ('TGI_RUFISQUE_CORRECTIONNELLE', 'TGI Rufisque - Correctionnelle'), ('TGI_RUFISQUE_INSTRUCTION', 'TGI Rufisque - Instruction'), ('TGI_KEUR_MASSAR_CIVIL', 'TGI Keur Massar - Civil'), ('TGI_KEUR_MASSAR_FDTR', 'TGI Keur Massar - FDTR'), ('TGI_KEUR_MASSAR_CORRECTIONNELLE', 'TGI Keur Massar - Correctionnelle'), ('TGI_KEUR_MASSAR_INSTRUCTION', 'TGI Keur Massar - Instruction'), ('TRAVAIL_DAKAR', 'Tribunal du Travail Dakar'), ('TRAVAIL_PIKINE', 'Tribunal du Travail Pikine'), ('TRAVAIL_RUFISQUE', 'Tribunal du Travail Rufisque'), ('TRIBUNAL_COMMERCE_DAKAR', 'Tribunal de Commerce de Dakar'), ('CA_CORRECTIONNEL', 'CA Correctionnel'), ('CA_CRIMINELLE', 'CA Criminelle'), ('CA_SOCIAL', 'CA Social'), ('COUR_SUPREME', 'Cour Suprême'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Type de chambre'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('COMMERCIAL', 'Commercial'), ('SOCIAL', 'Social'), ('PENAL', 'Pénal'), ('CORRECTIONNEL', 'Correctionnel'), ('TI_FAMILLE', 'TI Famille')], default='CIVIL', max_length=20, verbose_name='Catégorie'),
        ),
    ]
