# Generated by Django 6.0.1 on 2026-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_agendaevent_type_chambre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Référence dossier'),
        ),
    ]
