# Generated by Django 6.0.1 on 2026-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_case_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence dossier'),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('reference', 'category')},
        ),
    ]
