# Generated by Django 6.0 on 2025-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AVOCAT', 'Avocat'), ('COLLABORATEUR', 'Collaborateur'), ('STAGIAIRE', 'Stagiaire'), ('SECRETAIRE', 'Secrétaire'), ('CLIENT', 'Client')], default='COLLABORATEUR', max_length=20, verbose_name='Rôle'),
        ),
    ]
