# Generated by Django 6.0 on 2026-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AVOCAT', 'Avocat'), ('COLLABORATEUR', 'Collaborateur'), ('STAGIAIRE', 'Stagiaire'), ('SECRETAIRE', 'Secrétaire'), ('CLIENT', 'Client')], max_length=20, primary_key=True, serialize=False, verbose_name='Rôle')),
                ('permissions', models.JSONField(default=dict, help_text="Stocke les permissions sous forme de JSON { 'permission_name': boolean }", verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Permission Rôle',
                'verbose_name_plural': 'Permissions Rôles',
            },
        ),
    ]
